name: "Early Fire Detection Benchmark"
description: "Comprehensive benchmark for early fire and smoke detection using multiple prompts and models"
version: "1.0"

# Prompts to test
prompts:
  - "early_fire_json"
  - "wildfire_confidence"
  - "detailed_sequence_analysis"

# Models to test (using available local Ollama models)
models:
  - "qwen2.5vl:7b"
  - "llama3.2-vision:latest"
  - "minicpm-v:latest"

# Datasets to use (using available test data)
datasets:
  - "test_sequences"
  - "images"

# Metrics to calculate
metrics:
  - "accuracy"
  - "precision"
  - "recall"
  - "f1_score"
  - "latency"
  - "bbox_iou"
  - "parse_success_rate"

# Engine configuration
engine_config:
  timeout: 120
  max_retries: 2
  temperature: 0.1

# Test configuration
test_config:
  max_images_per_sequence: 5
  iou_threshold: 0.4
  confidence_threshold: 0.5