auto_augment: randaugment
automatic_recovery: true
checkpoint_validation: true
cleanup_old_checkpoints: true
conf: null
copy_paste: 0.0
cos_lr: true
dataset_path: /data/sai-benchmark/RNA/data/verificator_dataset
degrees: 0.0
deterministic: true
device: auto
dnn: false
emergency_stop: true
epochs: 50
fliplr: 0.5
flipud: 0.0
half: false
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
iou: 0.7
lr0: 0.001
lrf: 0.01
max_checkpoints: 10
max_det: 300
mixup: 0.0
model_type: verificator
momentum: 0.937
mosaic: 1.0
nan_detection: true
num_workers: 16
optimizer: AdamW
patience: 20
perspective: 0.0
rect: false
robust_validation: true
save_dir: /data/sai-benchmark/RNA/training/runs
save_hybrid: true
save_json: true
save_period: 5
scale: 0.5
seed: 42
shear: 0.0
shuffle: true
translate: 0.1
val_period: 1
val_split: 0.2
validation_frequency: 1
verbose: true
warmup_bias_lr: 0.1
warmup_epochs: 3
warmup_momentum: 0.8
weight_decay: 0.0005
