backbone: efficientnet_b0
batch_size: 256
channels_last: true
compile_model: true
cudnn_benchmark: true
dataset_path: /data/sai-benchmark/RNA/data/verificator_dataset
deterministic: true
device: auto
dropout: 0.3
epochs: 50
grad_clip: 1.0
learning_rate: 0.0003
mixed_precision: true
model_type: verificator
num_classes: 2
num_workers: 64
optimizer: adamw
output_dir: /data/sai-benchmark/RNA/training/runs/verificator_a100_real
patience: 15
persistent_workers: true
pin_memory: true
prefetch_factor: 8
save_every: 5
scheduler: reduce_on_plateau
scheduler_patience: 5
seed: 42
temporal_frames: 1
tensor_cores: true
torch_compile: true
use_class_weights: true
weight_decay: 1.0e-05
